services:
  php_fpm:
      build:
        context: .
        dockerfile: Dockerfile.wss
      user: 1000:1000
      container_name: chess_server_php_fpm
      ports:
          - ${WSS_PORT}:${WSS_PORT}
      restart: always
      volumes:
          - ./:/usr/share/chess-server
          - /usr/share/chess-server/vendor
          - ./docker/php/8.2/cli/php.ini:/usr/local/etc/php/php.ini
      working_dir: /usr/share/chess-server
