services:
  php_fpm:
      build:
        context: .
        dockerfile: Dockerfile.tcp
      user: "${UID}:${GID}"
      container_name: chess_server_php_fpm
      ports:
          - ${TCP_PORT}:${TCP_PORT}
      restart: always
      volumes:
          - ./:/usr/share/chess-server
          - ./docker/php/8.2/cli/php.ini:/usr/local/etc/php/php.ini
      working_dir: /usr/share/chess-server
