site_name: PHP Chess Server
site_url: https://chesslablab.github.io/chess-server/
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Game:
    - /draw: draw.md
    - /leave: leave.md
    - /rematch: rematch.md
    - /resign: resign.md
    - /takeback: takeback.md
    - /accept: accept.md
    - /legal: legal.md
    - /play_lan: play-lan.md
    - /randomizer: randomizer.md
    - /restart: restart.md
    - /start: start.md
    - /stockfish: stockfish.md
    - /undo: undo.md
    - /online_games: online-games.md
  - Data:
    - /annotations_game: annotations-game.md
    - /autocomplete_black: autocomplete-black.md
    - /autocomplete_event: autocomplete-event.md
    - /autocomplete_white: autocomplete-white.md
    - /result_event: result-event.md
    - /result_player: result-player.md
    - /result: result.md
    - /search: search.md
  - Binary:
    - /image: image.md
  - Auth:
    - /totp_refresh: totp-refresh.md
    - /totp_signin: totp-signin.md
    - /totp_signup: totp-signup.md

theme: readthedocs
