site_name: PHP Chess Server
site_url: https://chesslablab.github.io/chess-server/
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Game:
    - Text-based:
      - /eval_names: eval-names.md
      - /online_games: online-games.md
      - /undo: undo.md
    - Action-based:
      - /draw: draw.md
      - /rematch: rematch.md
      - /takeback: takeback.md
    - Param-based:
      - /accept: accept.md
      - /heuristic: heuristic.md
      - /leave: leave.md
      - /legal: legal.md
      - /play_lan: play-lan.md
      - /play_rav: play-rav.md
      - /randomizer: randomizer.md
      - /resign: resign.md
      - /restart: restart.md
      - /start: start.md
      - /stockfish: stockfish.md
      - /tutor_fen: tutor-fen.md
  - Data:
    - Text-based:
      - /annotations_game: annotations-game.md
      - /ranking: ranking.md
      - /result: result.md
    - Param-based:
      - /autocomplete_black: autocomplete-black.md
      - /autocomplete_event: autocomplete-event.md
      - /autocomplete_white: autocomplete-white.md
      - /result_event: result-event.md
      - /result_player: result-player.md
      - /search: search.md
  - Binary:
    - Param-based:
      - /image: image.md
  - Auth:
    - Text-based:
      - /totp_signup: totp-signup.md
    - Param-based:
      - /totp_refresh: totp-refresh.md
      - /totp_signin: totp-signin.md

theme: mkdocs
