site_name: PHP Chess Server
site_url: https://chesslablab.github.io/chess-server/
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Game:
    - /start: start.md
    - /legal: legal.md
    - /play_lan: play-lan.md
    - /undo: undo.md
    - /accept: accept.md
    - /takeback: takeback.md
    - /draw: draw.md
    - /resign: resign.md
    - /leave: leave.md
    - /rematch: rematch.md
    - /restart: restart.md
    - /stockfish: stockfish.md
    - /online_games: online-games.md
    - /randomizer: randomizer.md
  - Data:
    - /annotations_game: annotations-game.md
    - /autocomplete_black: autocomplete-black.md
    - /autocomplete_event: autocomplete-event.md
    - /autocomplete_white: autocomplete-white.md
    - /search: search.md
    - /stats_event: stats-event.md
    - /stats_opening: stats-opening.md
    - /stats_player: stats-player.md

theme: readthedocs
